export const INDUSTRY_KEYWORDS: Record<string, string[]> = {
  ai: [
    "artificial intelligence",
    "machine learning",
    "deep learning",
    "LLM",
    "GPT",
    "neural network",
    "AI agents",
    "generative AI",
    "transformer models",
    "computer vision",
  ],
  tech: [
    "technology",
    "software",
    "startup",
    "SaaS",
    "cloud computing",
    "cybersecurity",
    "devops",
    "programming",
    "open source",
    "tech industry",
  ],
  health: [
    "healthcare",
    "medical",
    "wellness",
    "biotech",
    "digital health",
    "telemedicine",
    "mental health",
    "pharmaceutical",
    "clinical trials",
    "health tech",
  ],
  finance: [
    "fintech",
    "banking",
    "investment",
    "cryptocurrency",
    "stock market",
    "venture capital",
    "financial services",
    "payments",
    "insurance tech",
    "trading",
  ],
  climate: [
    "climate change",
    "sustainability",
    "renewable energy",
    "clean tech",
    "carbon footprint",
    "ESG",
    "green technology",
    "electric vehicles",
    "solar energy",
    "climate tech",
  ],
  crypto: [
    "cryptocurrency",
    "blockchain",
    "web3",
    "DeFi",
    "NFT",
    "Bitcoin",
    "Ethereum",
    "smart contracts",
    "decentralized",
    "crypto regulation",
  ],
};

export const INDUSTRY_NAMES: Record<string, string> = {
  ai: "AI & Machine Learning",
  tech: "Technology",
  health: "Health & Wellness",
  finance: "Finance & Fintech",
  climate: "Climate & Sustainability",
  crypto: "Crypto & Web3",
};
